platform :ios, '10.0'
use_frameworks!

target 'Overwatch Helper' do
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'PNChartSwift',:git => 'https://github.com/kevinzhow/PNChart-Swift.git'
    pod "CSStickyHeaderFlowLayout"
    pod 'FoldingCell'
    pod 'MMCardView'
end